springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    azure:
      cosmos:
        database: OrderStorage
  
azure:
  cosmosdb:
    uri: https://orderstorageaccount.documents.azure.com:443/
    key: ${PETSTORE_COSMOS_API_KEY}
    database: OrderStorage
management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
